### ISSUE TITLE
4/11/2016 ISSUES

### ISSUE THREAD

**Issue by cmkernan** [concham/The-Social-Network#1]
? Do we need to create the mySQL table using php, or can we just create the table ourselves using phpmyadmin and then use php to generate the information that will fill the table?
- Login Validation
- Registration Validation
- Setting a new password using sha1
  ? Do we need to allow the user to create their own new password, or should we generate a new password for them?

**Comment by lowriek** [comment]
You can create the table with phpmyadmin, however you should document it with a file with a create statement and one or more insert statement.  For example
CREATE TABLE student(
    ID  int not null auto_increment,
    firstname   varchar(15) not null,
    lastname    varchar(15) not null,
    major       varchar(15) not null,
    gradyear    int,
    gpa     float(3,2) unsigned,
    PRIMARY KEY(ID)
);
insert into STUDENT(firstname, lastname, major, gradyear, gpa) values ('joe', 'smith', 'cs', 2016, 3.5);
